package com.tangmj.demo.dao.mapper;

import com.tangmj.demo.dao.model.DicIndex;
import com.tangmj.demo.dao.model.DicIndexExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface DicIndexMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sys_dic_index
     *
     * @mbggenerated
     */
    int countByExample(DicIndexExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sys_dic_index
     *
     * @mbggenerated
     */
    int deleteByExample(DicIndexExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sys_dic_index
     *
     * @mbggenerated
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sys_dic_index
     *
     * @mbggenerated
     */
    int insert(DicIndex record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sys_dic_index
     *
     * @mbggenerated
     */
    int insertSelective(DicIndex record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sys_dic_index
     *
     * @mbggenerated
     */
    List<DicIndex> selectByExample(DicIndexExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sys_dic_index
     *
     * @mbggenerated
     */
    DicIndex selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sys_dic_index
     *
     * @mbggenerated
     */
    int updateByExampleSelective(@Param("record") DicIndex record, @Param("example") DicIndexExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sys_dic_index
     *
     * @mbggenerated
     */
    int updateByExample(@Param("record") DicIndex record, @Param("example") DicIndexExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sys_dic_index
     *
     * @mbggenerated
     */
    int updateByPrimaryKeySelective(DicIndex record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sys_dic_index
     *
     * @mbggenerated
     */
    int updateByPrimaryKey(DicIndex record);
}