package com.tangmj.demo.dao.mapper;

import com.tangmj.demo.dao.model.Performance;
import com.tangmj.demo.dao.model.PerformanceExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface PerformanceMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sys_performance
     *
     * @mbggenerated
     */
    int countByExample(PerformanceExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sys_performance
     *
     * @mbggenerated
     */
    int deleteByExample(PerformanceExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sys_performance
     *
     * @mbggenerated
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sys_performance
     *
     * @mbggenerated
     */
    int insert(Performance record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sys_performance
     *
     * @mbggenerated
     */
    int insertSelective(Performance record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sys_performance
     *
     * @mbggenerated
     */
    List<Performance> selectByExampleWithBLOBs(PerformanceExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sys_performance
     *
     * @mbggenerated
     */
    List<Performance> selectByExample(PerformanceExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sys_performance
     *
     * @mbggenerated
     */
    Performance selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sys_performance
     *
     * @mbggenerated
     */
    int updateByExampleSelective(@Param("record") Performance record, @Param("example") PerformanceExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sys_performance
     *
     * @mbggenerated
     */
    int updateByExampleWithBLOBs(@Param("record") Performance record, @Param("example") PerformanceExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sys_performance
     *
     * @mbggenerated
     */
    int updateByExample(@Param("record") Performance record, @Param("example") PerformanceExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sys_performance
     *
     * @mbggenerated
     */
    int updateByPrimaryKeySelective(Performance record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sys_performance
     *
     * @mbggenerated
     */
    int updateByPrimaryKeyWithBLOBs(Performance record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sys_performance
     *
     * @mbggenerated
     */
    int updateByPrimaryKey(Performance record);
}