package com.tangmj.demo.dao.model;

import java.io.Serializable;
import java.util.Date;

public class Performance implements Serializable {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sys_performance.id
     *
     * @mbggenerated
     */
    private Integer id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sys_performance.method_name
     *
     * @mbggenerated
     */
    private String methodName;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sys_performance.class_name
     *
     * @mbggenerated
     */
    private String className;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sys_performance.create_time
     *
     * @mbggenerated
     */
    private Date createTime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sys_performance.method_param
     *
     * @mbggenerated
     */
    private String methodParam;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sys_performance.time_cost
     *
     * @mbggenerated
     */
    private String timeCost;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table sys_performance
     *
     * @mbggenerated
     */
    private static final long serialVersionUID = 1L;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sys_performance.id
     *
     * @return the value of sys_performance.id
     *
     * @mbggenerated
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sys_performance.id
     *
     * @param id the value for sys_performance.id
     *
     * @mbggenerated
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sys_performance.method_name
     *
     * @return the value of sys_performance.method_name
     *
     * @mbggenerated
     */
    public String getMethodName() {
        return methodName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sys_performance.method_name
     *
     * @param methodName the value for sys_performance.method_name
     *
     * @mbggenerated
     */
    public void setMethodName(String methodName) {
        this.methodName = methodName == null ? null : methodName.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sys_performance.class_name
     *
     * @return the value of sys_performance.class_name
     *
     * @mbggenerated
     */
    public String getClassName() {
        return className;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sys_performance.class_name
     *
     * @param className the value for sys_performance.class_name
     *
     * @mbggenerated
     */
    public void setClassName(String className) {
        this.className = className == null ? null : className.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sys_performance.create_time
     *
     * @return the value of sys_performance.create_time
     *
     * @mbggenerated
     */
    public Date getCreateTime() {
        return createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sys_performance.create_time
     *
     * @param createTime the value for sys_performance.create_time
     *
     * @mbggenerated
     */
    public void setCreateTime(Date createTime) {
        this.createTime = createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sys_performance.method_param
     *
     * @return the value of sys_performance.method_param
     *
     * @mbggenerated
     */
    public String getMethodParam() {
        return methodParam;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sys_performance.method_param
     *
     * @param methodParam the value for sys_performance.method_param
     *
     * @mbggenerated
     */
    public void setMethodParam(String methodParam) {
        this.methodParam = methodParam == null ? null : methodParam.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sys_performance.time_cost
     *
     * @return the value of sys_performance.time_cost
     *
     * @mbggenerated
     */
    public String getTimeCost() {
        return timeCost;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sys_performance.time_cost
     *
     * @param timeCost the value for sys_performance.time_cost
     *
     * @mbggenerated
     */
    public void setTimeCost(String timeCost) {
        this.timeCost = timeCost == null ? null : timeCost.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sys_performance
     *
     * @mbggenerated
     */
    @Override
    public boolean equals(Object that) {
        if (this == that) {
            return true;
        }
        if (that == null) {
            return false;
        }
        if (getClass() != that.getClass()) {
            return false;
        }
        Performance other = (Performance) that;
        return (this.getId() == null ? other.getId() == null : this.getId().equals(other.getId()))
            && (this.getMethodName() == null ? other.getMethodName() == null : this.getMethodName().equals(other.getMethodName()))
            && (this.getClassName() == null ? other.getClassName() == null : this.getClassName().equals(other.getClassName()))
            && (this.getCreateTime() == null ? other.getCreateTime() == null : this.getCreateTime().equals(other.getCreateTime()))
            && (this.getMethodParam() == null ? other.getMethodParam() == null : this.getMethodParam().equals(other.getMethodParam()))
            && (this.getTimeCost() == null ? other.getTimeCost() == null : this.getTimeCost().equals(other.getTimeCost()));
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sys_performance
     *
     * @mbggenerated
     */
    @Override
    public int hashCode() {
        final int prime = 31;
        int result = 1;
        result = prime * result + ((getId() == null) ? 0 : getId().hashCode());
        result = prime * result + ((getMethodName() == null) ? 0 : getMethodName().hashCode());
        result = prime * result + ((getClassName() == null) ? 0 : getClassName().hashCode());
        result = prime * result + ((getCreateTime() == null) ? 0 : getCreateTime().hashCode());
        result = prime * result + ((getMethodParam() == null) ? 0 : getMethodParam().hashCode());
        result = prime * result + ((getTimeCost() == null) ? 0 : getTimeCost().hashCode());
        return result;
    }
}